
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework: ERROR
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg% '
  logback:
    rollingpolicy:
      max-file-size: 20MB
  file:
    name: /logs/messages-cache.tmp
    path:
resources:
  auth-url: ${AUTHORIZATION_URL}